# Generated by Django 4.0.5 on 2022-06-21 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14)),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('logo', models.ImageField(upload_to='')),
                ('site', models.URLField()),
                ('whatsapp', models.CharField(max_length=12)),
                ('telefone', models.CharField(blank=True, max_length=12, null=True)),
                ('cidade', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.loja')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=4)),
                ('preco_promocao', models.DecimalField(decimal_places=2, max_digits=4)),
                ('data_inicial', models.DateTimeField(auto_now_add=True)),
                ('data_final', models.DateTimeField()),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.loja')),
            ],
        ),
    ]
