# Generated by Django 4.0.5 on 2022-06-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocao',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='preco_promocao',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
