# Generated by Django 4.0.5 on 2022-06-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_alter_promocao_preco_alter_promocao_preco_promocao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='loja',
        ),
        migrations.AddField(
            model_name='usuario',
            name='loja',
            field=models.ManyToManyField(related_name='usuario', to='loja.loja'),
        ),
    ]
